/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


#include "stdint.h"
#include "stdlib.h"
#include "stdio.h"

//GPIOA register address
#define GPIOA_BASE					0x40010800

#define GPIOA_CRH					*(volatile uint32_t *)(GPIOA_BASE + 0x04)
#define GPIOA_ODR					*(volatile uint32_t *)(GPIOA_BASE + 0x0C)
#define GPIOA_CRL					*(volatile uint32_t *)(GPIOA_BASE + 0x00)
#define GPIOA_IDR					*(volatile uint32_t *)(GPIOA_BASE + 0x08)


//GPIOB register address
#define GPIOB_BASE					0x40010C00

#define GPIOB_CRH					*(volatile uint32_t *)(GPIOB_BASE + 0x04)
#define GPIOB_ODR					*(volatile uint32_t *)(GPIOB_BASE + 0x0C)
#define GPIOB_CRL					*(volatile uint32_t *)(GPIOB_BASE + 0x00)
#define GPIOB_IDR					*(volatile uint32_t *)(GPIOB_BASE + 0x08)


//clk reg. address
#define RCC_BASE 					0x40021000

#define RCC_APB2ENR					*(volatile uint32_t *)(RCC_BASE + 0x18)
#define RCC_CFGR					*(volatile uint32_t *)(RCC_BASE + 0x04)
#define RCC_CR						*(volatile uint32_t *)(RCC_BASE + 0x00)


void clock_init(){
	//enable clock of portA
	RCC_APB2ENR |= 1 << 2;

	//enable clock of portB
	RCC_APB2ENR |= 1 << 3;

}

void GPIO_init(){

	/*input : floating point, output: push-pull*/

	//configure Pin A1 as input: 0100
	GPIOA_CRL &= ~(0b1011<<4);
	GPIOA_CRL |= 1 << 6;

	//configure Pin A13 as input : 0100
	GPIOA_CRH &= ~(0b1011 << 20);
	GPIOA_CRH |= 1 << 22;

	//configure Pin B1 as output:0001
	GPIOB_CRL &= ~(0b1110 << 4);
	GPIOB_CRL |= 1 << 4;

	//configure Pin B13 as output:0001
	GPIOB_CRH &= ~(0b1110 << 20);
	GPIOB_CRH |= 1 << 20;

	//reset, led is ON
	//GPIOB_ODR &= ~(1<<1);
	//GPIOB_ODR &= ~(1<<13);

}

void wait(uint32_t t){
	uint32_t i,j;
	for(i = 0; i < t; i++)
		for(j=0; j < 255; j++);
}

int main(void)
{

	clock_init();
	GPIO_init();


	while(1){
		if(((GPIOA_IDR &= (1<<1)) >> 1) == 0){ //press A1 (PUR)

			GPIOB_ODR ^= 1<<1;
			while(((GPIOA_IDR &= (1<<1)) >> 1) == 0); //single pressing
		}

		if(((GPIOA_IDR &= (1<<13)) >> 13) == 1){ //press A13 (PDR)

			GPIOB_ODR ^=  1<<13;
			//multiple pressing

			wait(1);

		}
	}


}

