/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "stm32f103c6_exti_driver.h"
#include "STM32F103C6_Header_Driver.h"
#include "keyPad.h"
#include "lcd.h"
#include "stm32f103c6_gpio_driver.h"


unsigned int IRQ_flag;

void my_wait(uint32_t time)
{
	int i,j;
	for(i = 0; i< time; i++)
		for(j = 0; j<255; j++);
}


void EXTI9_callback(void)
{
	LCD_clear_screen();
	IRQ_flag = 1;
	LCD_WRITE_STRING("IRQ EXTI9 is happened _|-");
	my_wait(1000);
}

int main(void)
{
	RCC_GPIOA_CLK_EN();
	RCC_GPIOB_CLK_EN();
	RCC_AFIO_CLK_EN();



	EXTI_PinConfig_t EXTI_CFG;
	EXTI_CFG.EXTI_PIN = EXTI9PB9;
	EXTI_CFG.Trigger_case = EXTI_Trigger_RISING;
	EXTI_CFG.p_IRQ_callBack = EXTI9_callback;
	EXTI_CFG.IRQ_EN = EXTI_IRQ_ENABLE;

	MCAL_EXTI_Init(&EXTI_CFG);

	LCD_INIT();
	LCD_clear_screen();

	IRQ_flag = 1;
	/* Loop forever */
	while(1)
	{
		if(IRQ_flag)
		{
			LCD_clear_screen();
			IRQ_flag = 0;
		}
	}
}
