/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

//Learn-in-depth
//Keroles Shenouda
//Mastering_Embedded System online diploma

#include "STM32F103C6_Header_Driver.h"
#include "stm32f103c6_gpio_driver.h"
#include "lcd.h"
#include "keyPad.h"
#include "7_segment.h"

/*7 segment*/
#define ZERO 0x01
#define ONE 0x79
#define TWO 0x24
#define THREE 0x30
#define FOUR 0x4C
#define FIVE 0x12
#define SIX 0x02
#define SEVEN 0x19
#define EIGHT 0x00
#define NINE 0x10

void clock_init() {
	//Enable clock GPIOA
	RCC_GPIOA_CLK_EN();
	//Enable clock GPIOB Bit 3 IOPBEN: IO port B clock enable
	RCC_GPIOB_CLK_EN();
}
void wait_ms(uint32_t time) {
	uint32_t i, j;
	for (i = 0; i < time; i++)
		for (j = 0; j < 255; j++)
			;
}
int main(void) {

	clock_init();
	LCD_INIT();

	SEG_INIT();
	LCD_WRITE_STRING("Keypad is ready");
	wait_ms(500);
	LCD_clear_screen();

	unsigned char key;
	unsigned char seg [] = {ZERO, ONE, TWO, THREE,FOUR, FIVE, SIX, SEVEN, EIGHT, NINE, ZERO};
	unsigned char lcd[] = {'0','1','2', '3', '4', '5', '6', '7', '8', '9', '0'};
	//7 segment
	for(unsigned int i = 0; i < 11; i++){
		MCAL_GPIO_WritePort(GPIOB, seg[i] << 9);
		LCD_WRITE_CHAR(lcd[i]);
		wait_ms(100);
	}
	LCD_clear_screen();
	KEYPAD_INIT();
	while (1) {

		key = KEYPAD_GET_CHAR();
		switch(key){
		case '!':
			LCD_clear_screen();
			break;

		case 'N':
			break;

		default:
			LCD_WRITE_CHAR(key);
			break;
		}

	}

}
